config/routes.rb
Tigris::Application.routes.draw do

  resources :searches

  get "sessions/new"
  get "session/new"
  get "page/home"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "page#home"

  post '/events/register' => 'events#register', :as => :register
  post '/events/unregister' => 'events#unregister', :as => :unregister

  post 'pages/contact' => 'page#send_mail', :as => :message
  match 'calendar' => 'page#calendar', :as => :calendar
  match 'contact' => 'page#contact', :as => :contact

  get 'users/search' => 'users#detail_search', :as => :users_search
  post 'users/search' => 'users#search', :as => :users_search

  resources :events
  resources :news
  resources :organizations
  resources :users
  resources :sessions
  resources :messages

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :participations
  has_many :users, :through => :participations

  def applied? (user)
    if user.nil?
      return false
    end
    if self.users.find_by_id(user.id)
      return true
    else
      return false
    end
  end

# Convert to iCalendar
  def to_ics
    event = Icalendar::Event.new
    event.start = self.start_date.strftime("%Y%m%dT%H%M%S")
    event.end = self.end_date.strftime("%Y%m%dT%H%M%S")
    event.summary = self.name
    event.description = self.description
    event.location = self.location
    event.klass = "PUBLIC"
#    event.created = self.created_at
#    event.last_modified = self.updated_at
    event.uid = event.url = "#{PUBLIC_URL}events/#{self.id}"
    event
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate, :only => [:new, :edit, :update]
  # GET /events
  # GET /events.xml
  def index
    @events = Event.find(:all, :order => "start_date DESC")

    @title = 'Događaji'
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.ical do
        calendar = Icalendar::Calendar.new
        @events.each do |event|
          calendar.add_event(event.to_ics)
          calendar.publish
          calendar.to_ical
          #render 'calendar.to_ical'
          #redirect_to root_path
        end
        render :text => calendar.to_ical
      end
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    @title = @event.name
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
      format.ics do
        calendar = Icalendar::Calendar.new
        calendar.add_event(@event.to_ics)
        calendar.publish
        calendar.to_ical
        #render 'calendar.to_ical'
        #redirect_to root_path
        render :text => calendar.to_ical
      end
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    @title = 'Novi događaj'
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    if authorized_for @event
      @title = 'Izmjena detalja događaja'
    else
      redirect_to event_path(@event), :notice => 'Nemate dovoljno prava za ovu akciju.'
    end
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])
    start_date = Date.strptime(params[:start_date], "%d/%m/%Y")
    start_time = params[:start_time]
    @event.start_date = "#{start_date} #{start_time}"
    end_date = Date.strptime(params[:end_date], "%d/%m/%Y")
    end_time = params[:end_time]
    @event.end_date = "#{end_date} #{end_time}"

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])
    start_date = Date.strptime(params[:start_date], "%d/%m/%Y")
    start_time = params[:start_time]
    @event.start_date = "#{start_date} #{start_time}"
    end_date = Date.strptime(params[:end_date], "%d/%m/%Y")
    end_time = params[:end_time]
    @event.end_date = "#{end_date} #{end_time}"

    if authorized_for @event
      respond_to do |format|
        if @event.update_attributes(params[:event])
          format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
        end
      end
    else
      redirect_to :back, :notice => 'Nemate dovoljno prava za ovu akciju.'
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    if authorized_for @event
      @event.destroy

      respond_to do |format|
        format.html { redirect_to(events_url) }
        format.xml  { head :ok }
      end
    else
      redirect_to :back, :notice => 'Nemate dovoljno prava za ovu akciju.'
    end
  end

  def register
    @event = Event.find_by_id(params[:event_id])
    @event.users.push(current_user)
    respond_to do |format|
      format.html { redirect_to event_path(@event) }
      format.xml  { render :xml => @events }
    end
  end

  def unregister
    @event = Event.find_by_id(params[:event_id])
    participation = @event.participations.find_by_user_id(current_user.id)
    @event.participations.delete(participation)
    respond_to do |format|
      format.html { redirect_to event_path(@event) }
      format.xml  { render :xml => @events }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  -if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .input
    .field
      = f.label :name, 'Naziv'
      %br
      = f.text_field :name
    .field
      = f.label :location, 'Mjesto'
      %br
      = f.text_field :location
    .field
      = label_tag :start_date, 'Početak'
      %br
        = text_field_tag :start_date, @event.start_date.nil? ? nil : @event.start_date.strftime("%d/%m/%Y")
        &nbsp;u
        = text_field_tag :start_time, @event.start_date.nil? ? nil : @event.start_date.strftime("%H:%M")
    .field
      = label_tag :end_date, 'Završetak'
      %br
        = text_field_tag :end_date, @event.end_date.nil? ? nil : @event.end_date.strftime("%d/%m/%Y")
        &nbsp;u
        = text_field_tag :end_time, @event.end_date.nil? ? nil : @event.end_date.strftime("%H:%M") unless @event.nil?
      :javascript
        $(function(){
        $('#start_date, #start_time,' + '#end_date, #end_time').calendricalDateTimeRange({usa: false,
                                                                                          isoTime: true,
                                                                                          minTime: {hour: 0, minute: 0},
                                                                                          defaultTime: {hour: 15, minute: 0}
                                                                                          });
        })
    .field
      = f.label :description, 'Opis'
      %br
      = f.text_area :description
    .actions
      = f.submit 'Pošalji'

app/views/events/edit.html.haml
%h1= @title

= render 'form'

app/views/events/index.html.haml
%h1= @title

%table
  %tr
    %th Naziv
    %th Početak
    %th Kraj
    %th Mjesto

  - @events.each do |event|
    %tr{:class => cycle('odd', 'even')}
      %td= link_to event.name, event
      %td= event.start_date.strftime("%d.%m.%Y u %H:%M")
      %td= event.end_date.strftime("%d.%m.%Y u %H:%M")
      %td= event.location
%br

- content_for :sidebar do
  - if admin?
    %p= link_to 'Dodaj događaj', new_event_path

app/views/events/new.html.haml
%h1= @title

= render 'form'

app/views/events/show.html.haml
%p#notice= notice

%h1= @title

%p
  %b Počinje
  = @event.start_date.strftime("%d.%m.%Y u %H:%M")
%p
  %b Završava
  = @event.end_date.strftime("%d.%m.%Y u %H:%M")
%p
  %b Mjesto:
  = @event.location

%p
  %b Opis:
  - if @event.description.empty?
    %p Nema opisa događaja
  - else
    .rounded-box= simple_format h(@event.description)

-if current_user
  -if @event.applied? current_user
    -form_tag ("#{unregister_path}") do
      %input{:name => "event_id", :value => @event.id, :type => "hidden"}
      %input{:name => "user_id", :value => current_user.id, :type => "hidden"}
      = submit_tag 'Odjava'
  -else
    -form_tag ("#{register_path}") do
      %input{:name => "event_id", :value => @event.id, :type => "hidden"}
      %input{:name => "user_id", :value => current_user.id, :type => "hidden"}
      = submit_tag 'Prijava'

- if @event.users.empty?
  %p Nema prijavljenih na događaj
- else
  %p
    %b Sudionici:
  %table
    %tr
      %th Prezime i ime
      %th Email
      %th Telefon
    - @event.users.each do |user|
      %tr{:class => cycle('odd', 'even')}
        %td= link_to "#{user.surname} #{user.name}", user
        %td= user.email
        %td= user.phone

- content_for :sidebar do
  - if admin?
    %p
      = link_to 'Dodaj događaj', new_event_path
  - if authorized_for @event
    %p
      = link_to 'Izmijeni događaj', edit_event_path(@event)
    %p
      = link_to 'Obriši događaj', @event, :confirm => 'Are you sure?', :method => :delete