config/routes.rb
Tigris::Application.routes.draw do

  resources :searches

  get "sessions/new"
  get "session/new"
  get "page/home"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "page#home"

  post '/events/register' => 'events#register', :as => :register
  post '/events/unregister' => 'events#unregister', :as => :unregister

  post 'pages/contact' => 'page#send_mail', :as => :message
  match 'calendar' => 'page#calendar', :as => :calendar
  match 'contact' => 'page#contact', :as => :contact

  get 'users/search' => 'users#detail_search', :as => :users_search
  post 'users/search' => 'users#search', :as => :users_search

  resources :events
  resources :news
  resources :organizations
  resources :users
  resources :sessions
  resources :messages

end

app/views/page/calendar.html.haml
%h1= @title
<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showTz=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=gs0rba2h2piei0gaiodcd2vdg4ch3c33%40import.calendar.google.com&amp;color=%238C500B&amp;ctz=Europe%2FBelgrade" style=" border-width:0 " width="900" height="500" frameborder="0" scrolling="no"></iframe>


= @event_calendar

app/views/page/contact.html.haml
%p#notice= notice

%h1= @title

= form_for @message, :url => { :action => "send_mail" } do |f|

  .field
    =f.label 'Tema'
    %br
    =f.text_field :subject

  .field
    =f.label 'Vaše ime'
    %br
    =f.text_field :sender_name

  .field
    =f.label 'Email'
    %br
    =f.text_field :sender_email

  .field
    =f.label 'Sadržaj'
    %br
    =f.text_area :body

  .actions
    = f.submit 'Pošalji'

- content_for :sidebar do

  %p
    %b
      Udruga studenata
  %p
    %b
      Adresa
  %p
    Unska 3
  %p
    10000 Zagreb
  %p
    %b
      Telefon
  %p
    +385 1 234 5678

  %p
    %b
      Gdje se nalazimo

  <iframe width="250" height="240" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps/ms?ie=UTF8&amp;hl=en&amp;msa=0&amp;msid=204619001471985298742.0004a4ad79b6d8be2ed00&amp;ll=45.801969,15.970559&amp;spn=0.00718,0.010686&amp;z=15&amp;output=embed"></iframe><br /><small>View <a href="http://maps.google.com/maps/ms?ie=UTF8&amp;hl=en&amp;msa=0&amp;msid=204619001471985298742.0004a4ad79b6d8be2ed00&amp;ll=45.801969,15.970559&amp;spn=0.00718,0.010686&amp;z=15&amp;source=embed" style="color:#0000FF;text-align:left">Udruga studenata</a> in a larger map</small>

app/views/page/home.html.haml
%h1= @title unless logged_in?

#news.rounded-box
  %h3 Obavijesti
  - unless @news.nil? or @news.empty?
    - @news.each do |news|
      %p
        = link_to news.title, news_path(news)
        %br/
        objavljeno: #{news.created_at.strftime("%d.%m.%Y u %H:%M")}
        %br/
        = news.summary
    - if @news_counter > 4
      %p
        = link_to "Sve obavijesti &raquo;".html_safe, news_index_path
#events.rounded-box
  %h3 Događaji
  - if @events.nil? or @events.empty?
    %p
      Nema nadolazećih događaja
  - else
    - @events.each do |event|
      %p
        = link_to event.name, event_path(event)
        %br/
        Datum: #{event.start_date.strftime("%d.%m.%Y")}

-content_for :sidebar do
  =render :partial => 'layouts/side_calendar'
  %p
    =link_to 'Kalendar događanja', calendar_path
  %p
    =link_to 'Preuzmi kalendar', 'events.ical'