config/routes.rb
Tigris::Application.routes.draw do

  resources :searches

  get "sessions/new"
  get "session/new"
  get "page/home"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "page#home"

  post '/events/register' => 'events#register', :as => :register
  post '/events/unregister' => 'events#unregister', :as => :unregister

  post 'pages/contact' => 'page#send_mail', :as => :message
  match 'calendar' => 'page#calendar', :as => :calendar
  match 'contact' => 'page#contact', :as => :contact

  get 'users/search' => 'users#detail_search', :as => :users_search
  post 'users/search' => 'users#search', :as => :users_search

  resources :events
  resources :news
  resources :organizations
  resources :users
  resources :sessions
  resources :messages

end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :user
  cattr_reader :per_page
  @@per_page = 5
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_filter :authenticate, :only => [:new, :edit, :update]
  # GET /news
  # GET /news.xml
  def index
    @news = News.paginate :page => params[:page], :order => "created_at DESC"
    @suggested_news = News.paginate :page => params[:suggested_page], :conditions => {:status => 'suggested'}, :order => "created_at DESC"
    @suggested_count = News.find(:all, :conditions => {:status => 'suggested'}).count
    @internal_news = News.paginate :page => params[:internal_page], :conditions => {:status => 'internal'}, :order => "created_at DESC"
    @public_news = News.paginate :page => params[:public_page], :conditions => {:status => 'public'}, :order => "created_at DESC"
    @title = 'Novosti'

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @news }
    end
  end

  # GET /news/1
  # GET /news/1.xml
  def show
    @news = News.find(params[:id])
    @title = @news.title
    @author = User.find_by_id(@news.user_id)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @news }
    end
  end

  # GET /news/new
  # GET /news/new.xml
  def new
    @news = News.new
    @title = 'Nova obavijest'

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
    if authorized_for @news
      @title = 'Izmjena detalja novosti'
    else
      redirect_to news_path(@news), :notice => 'Nemate dovoljno prava za ovu akciju.'
    end
  end

  # POST /news
  # POST /news.xml
  def create
    @news = News.new(params[:news])
    @news.user_id = current_user.id

    unless admin?
      @news.status = 'suggested'
    end

    respond_to do |format|
      if @news.save
        format.html { redirect_to(@news, :notice => 'News was successfully created.') }
        format.xml  { render :xml => @news, :status => :created, :location => @news }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @news.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.xml
  def update
    @news = News.find(params[:id])
    if authorized_for @news
      respond_to do |format|
        if @news.update_attributes(params[:news])
          format.html { redirect_to(@news, :notice => 'News was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @news.errors, :status => :unprocessable_entity }
        end
      end
    else
      redirect_to :back, :notice => 'Nemate dovoljno prava za ovu akciju.'
    end
  end

  # DELETE /news/1
  # DELETE /news/1.xml
  def destroy
    @news = News.find(params[:id])
    if authorized_for @news
      @news.destroy

      respond_to do |format|
        format.html { redirect_to(news_index_url) }
        format.xml  { head :ok }
      end
    else
      redirect_to :back, :notice => 'Nemate dovoljno prava za ovu akciju.'
    end
  end
end

app/helpers/news_helper.rb
module NewsHelper

  def translate status
    if status == 'public'
      return 'javno'
    elsif status == 'suggested'
      return 'predloženo'
    elsif status == 'internal'
      return 'interno'
    elsif status == 'hidden'
      return 'skriveno'
    else
      return status
    end
  end

end

app/views/news/_form.html.haml
%table
= form_for @news do |f|
  -if @news.errors.any?
    #error_explanation
      %h2= "#{pluralize(@news.errors.count, "error")} prohibited this news from being saved:"
      %ul
        - @news.errors.full_messages.each do |msg|
          %li= msg
  %tr
    %td
      .field
        = f.label :title, 'Naslov'
    %td
      = f.text_field :title
  %tr
    %td
      .field
        = f.label :summary, 'Sažetak'
    %td
      = f.text_field :summary
  %tr
    %td
      .field
        = f.label :text, 'Sadržaj'
    %td
      = f.text_area :text
  - if admin?
    %tr
      %td
        .field
          = f.label :status, 'Status'
      %td
        = select :news, :status, [["Predloženo",'suggested'], ["Javno",'public'], ["Interno",'internal'], ["Skriveno",'hidden']]
  %br
  %tr
    %td
    %td
      .actions
        = f.submit 'Spremi'

app/views/news/_news_table.html.haml
%table
  %tr
    %th Datum
    %th Naslov
    %th Autor
    - if admin?
      %th Status

  - news.each do |news|
    %tr{:class => cycle('odd', 'even')}
      %td= news.created_at.strftime("%d.%m.%Y.")
      %td= link_to news.title, news_path(news)
      %td= logged_in? ? (link_to "#{news.user.name} #{news.user.surname}", user_path(news.user)) : ("#{news.user.name} #{news.user.surname}") unless news.user.nil?
      - if admin?
        %td= translate news.status

app/views/news/edit.html.haml
%h1= @title

= render 'form'

app/views/news/index.html.haml
- if admin?
  - unless @suggested_news.nil? or @suggested_news.empty?
    %h3
      Predložene obavijesti
    = render :partial => 'news_table', :locals => {:news => @suggested_news}
    = will_paginate @suggested_news, :param_name => 'suggested_page'

- if admin?
  %h3
    Sve obavijesti
  = render :partial => 'news_table', :locals => {:news => @news}
  = will_paginate @news
-  else
  - if logged_in?
    %h3
      Interne obavijesti
    = render :partial => 'news_table', :locals => {:news => @internal_news}
    = will_paginate @internal_news, :param_name => 'internal_page'

  %h3
    Javne obavijesti
  = render :partial => 'news_table', :locals => {:news => @public_news}
  = will_paginate @public_news, :param_name => 'public_page'


%br

-content_for :sidebar do
  - if admin?
    - unless @suggested_news.nil? or @suggested_news.empty?
      %p
        Predloženih obavijesti: #{@suggested_count}
  %p
    = link_to admin? ? 'Dodaj obavijest' : 'Predloži obavijest', new_news_path

app/views/news/show.html.haml
%p#notice= notice

%h1= @title

%p
  Datum:
  = @news.created_at.strftime("%d.%m.%Y.")

- unless @author.nil?
  %p
    Autor:
    = logged_in? ? link_to ("#{@author.name} #{@author.surname}", @author ) : "#{@author.name} #{@author.surname}"

- unless @news.summary.nil? or @news.summary.empty?
  %p
    %b Sažetak
    %p
      = @news.summary
- unless (@news.text.nil? or @news.text.empty?)
  %b Sadržaj
  %div.rounded-box
    %p
      = simple_format h(@news.text)
- unless (@news.status.nil? or @news.status.empty?)
  %p
    %b Status
    = translate @news.status


-content_for :sidebar do

  -if logged_in?
    %p
      = link_to admin? ? 'Dodaj obavijest' : 'Predloži obavijest', new_news_path
    %p
      = link_to 'Izmjeni obavijest', edit_news_path(@news) if authorized_for @news
    %p
      = link_to 'Obriši obavijest', @news, :confirm => 'Jeste li sigurni?', :method => :delete if authorized_for @news