config/routes.rb
Tigris::Application.routes.draw do

  resources :searches

  get "sessions/new"
  get "session/new"
  get "page/home"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "page#home"

  post '/events/register' => 'events#register', :as => :register
  post '/events/unregister' => 'events#unregister', :as => :unregister

  post 'pages/contact' => 'page#send_mail', :as => :message
  match 'calendar' => 'page#calendar', :as => :calendar
  match 'contact' => 'page#contact', :as => :contact

  get 'users/search' => 'users#detail_search', :as => :users_search
  post 'users/search' => 'users#search', :as => :users_search

  resources :events
  resources :news
  resources :organizations
  resources :users
  resources :sessions
  resources :messages

end

app/views/layouts/_header.html.erb
<div id="header">
  <%= image_tag '/images/logo.jpg', :height => '115' %>
</div>

app/views/layouts/_navigation.html.erb
<div id="navigation">
  <div id="pages">
    <%= link_to 'Početna', root_path %>
    &nbsp;|&nbsp;<%= link_to 'Novosti', news_index_path %>
    <% if current_user %>
      &nbsp;|&nbsp;<%= link_to 'Događaji', events_path %>&nbsp;|&nbsp;
      <%= link_to 'Članovi', users_path %>&nbsp;|&nbsp;
      <%= link_to 'Timovi', organizations_path %>
    <% end %>
    &nbsp;|&nbsp;<%= link_to 'Kalendar', calendar_path %>
    &nbsp;|&nbsp;<%= link_to 'Kontakt', contact_path %>
  </div>
  <div id="nav_session">
    <% if current_user %>
      <%= link_to "#{current_user.name} #{current_user.surname}", current_user %>&nbsp;|&nbsp;
      <%= link_to 'Odjava', log_out_path %>
    <% else %>
      <%= link_to 'Novi korisnik', sign_up_path %>&nbsp;|&nbsp;
      <%= link_to 'Prijava', log_in_path %>
    <% end %>
  </div>
</div>

app/views/layouts/_side_calendar.html.haml
<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=240&amp;wkst=2&amp;hl=hr&amp;bgcolor=%23FFFFFF&amp;src=gs0rba2h2piei0gaiodcd2vdg4ch3c33%40import.calendar.google.com&amp;color=%238C500B&amp;ctz=Europe%2FBelgrade" style=" border-width:0 " width="250" height="240" frameborder="0" scrolling="no"></iframe>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tigris</title>
  <%= stylesheet_link_tag "style", "scaffold", "calendrical" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js" %>
  <%= javascript_include_tag "jquery.calendrical" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="wrapper">
    <%= render :partial => 'layouts/header' %>
    <%= render :partial => 'layouts/navigation' %>
    <div id="content">
      <% unless content_for(:left_bar).blank? %>
          <div id="left_bar">
            <%= yield :left_bar %>
         </div>
      <% end %>
      <div id="main_content">
        <%= yield %>
      </div>
      <% unless content_for(:sidebar).blank? %>
          <div id="sidebar">
            <%= yield :sidebar %>
         </div>
      <% end %>
    </div>
  </div>
</body>
</html>